name: Test nix build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check_nix:
    name: Test Nix
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      - name: Check flake
        run: nix flake check
      - name: Build with nix
        run: nix build
